server:
  port: 2015
  servlet:
    context-path: /dgpsn-api
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace:
      include-exception: false

    spring:
      datasource:
        name: ${DB_NAME:dgpsn-db}
        host: ${DB_HOST:185.166.39.101}
        username: ${DB_USERNAME:webgram-pg}
        password: ${DB_PASSWORD:Webgram2024#}
        url: jdbc:postgresql://${spring.datasource.host}:5432/${spring.datasource.name}?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true

      servlet:
        multipart:
          max-file-size: 30MB
          max-request-size: 30MB

      jpa:
        hibernate:
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          #      ddl-auto: create # Changer en << update >> d?s qu'on initialise la db
          ddl-auto: update # Changer en << update >> d?s qu'on initialise la db
        show-sql: false
      application:
        name: gestionrisque

    storage-document:
      file-storage-root-path: /home/webgram/formation/docs
      template-name: template.vm

    security-jwt:
      # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
      base64-secret: MmMzN2VlODJhN2U3NDk2NzQ2ZjE4Nzg3ZDkxYzg5ZDdkZDEwMTdjYWM3OWRiYjQwOWU4M2NiYTdmOThkYTU3OTI3Nzg2YTAwYTc2ODEyMzgwNjhiYTU2MTkyNDNmNWJiODc5Y2M4MWVhNjJhYTU3ZjRmNzEzZDhlZmYxNDlhYWM=
      # Token is valid 24 hours
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 86400

    webg-mail:
      enabled: false
      from: admin@admin.com
      base-url: http://localhost:4200

    gestionrisque-cors:
      cors:
        allowed-origins: "http://185.166.39.101:8088,http://185.166.39.101,http://185.166.39.101/"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,Content-Disposition"
        allow-credentials: true
        max-age: 1800